resolver: lts-7.14
compiler: ghc-8.0

nix:
  enable: true
  pure: true
  packages: []
  # shell-file: shell.nix

packages:
- .
- ../spiros

extra-deps:
- spiros-0.0.0
- dump-core-0.1.3  # hide behind flag?
